import os
import smtplib
import logging
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

logger = logging.getLogger(__name__)

class EmailService:
    @staticmethod
    def send_credentials_email(recipient_name: str, recipient_email: str, role: str, default_password: str, login_url: str = "http://localhost:5173/login"):
        """
        Sends account creation and default credentials email to new stakeholder.
        Uses environment SMTP settings if present; otherwise logs the email content safely.
        """
        subject = f"Welcome to VPM Platform - Account Access for {role}"
        
        html_body = f"""
        <!DOCTYPE html>
        <html>
        <head>
          <style>
            body {{ font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background-color: #0c1017; color: #e2e8f0; margin: 0; padding: 20px; }}
            .container {{ max-width: 600px; margin: 0 auto; background: #141a28; border: 1px solid rgba(255,255,255,0.1); border-radius: 16px; padding: 32px; }}
            .header {{ text-align: center; border-bottom: 1px solid rgba(255,255,255,0.08); padding-bottom: 20px; }}
            .brand {{ font-size: 24px; font-weight: 900; color: #ff5a14; letter-spacing: -0.5px; }}
            .sub {{ font-size: 11px; color: #94a3b8; text-transform: uppercase; letter-spacing: 1.5px; }}
            .content {{ margin-top: 24px; line-height: 1.6; font-size: 14px; color: #cbd5e1; }}
            .cred-box {{ background: #0e1320; border: 1px solid #ff5a14; border-radius: 12px; padding: 18px; margin: 20px 0; }}
            .cred-item {{ margin-bottom: 8px; font-size: 13px; }}
            .cred-label {{ color: #94a3b8; font-weight: 600; display: inline-block; width: 130px; }}
            .cred-val {{ font-family: monospace; font-weight: bold; color: #ff7a45; font-size: 14px; }}
            .btn {{ display: inline-block; padding: 12px 28px; background: linear-gradient(135deg, #ff5a14, #ff7a45); color: #ffffff !important; text-decoration: none; border-radius: 10px; font-weight: bold; font-size: 13px; margin: 15px 0; }}
            .footer {{ margin-top: 30px; font-size: 11px; color: #64748b; border-top: 1px solid rgba(255,255,255,0.08); padding-top: 15px; text-align: center; }}
          </style>
        </head>
        <body>
          <div class="container">
            <div class="header">
              <div class="brand">VPM PLATFORM</div>
              <div class="sub">Autonomous Enterprise Governance Suite</div>
            </div>
            <div class="content">
              <p>Dear <strong>{recipient_name}</strong>,</p>
              <p>You have been onboarded as a designated <strong>{role}</strong> stakeholder in the VPM (Virtual Project Manager) Governance Suite by the PMO Lead.</p>
              
              <p>Your workspace is configured with persona-tailored dashboards, risk registers, and approval gates. Below are your initial system login credentials:</p>
              
              <div class="cred-box">
                <div class="cred-item">
                  <span class="cred-label">Login URL:</span>
                  <span class="cred-val">{login_url}</span>
                </div>
                <div class="cred-item">
                  <span class="cred-label">Username / Email:</span>
                  <span class="cred-val">{recipient_email}</span>
                </div>
                <div class="cred-item">
                  <span class="cred-label">Assigned Role:</span>
                  <span class="cred-val">{role}</span>
                </div>
                <div class="cred-item">
                  <span class="cred-label">Password:</span>
                  <span class="cred-val">{default_password}</span>
                </div>
              </div>

              <div style="text-align: center;">
                <a href="{login_url}" class="btn">Sign In to VPM Workspace &rarr;</a>
              </div>

              <p style="font-size: 12px; color: #94a3b8; margin-top: 15px;">
                <strong>Security Notice:</strong> This is a temporary access credential. Please change your password upon your initial sign-in.
              </p>
            </div>
            <div class="footer">
              &copy; 2026 VPM Autonomous Platform &bull; Confidential &bull; Generated by PMO Governance Core
            </div>
          </div>
        </body>
        </html>
        """

        smtp_server = os.getenv("SMTP_SERVER", "smtp.gmail.com")
        smtp_port = int(os.getenv("SMTP_PORT", "587"))
        smtp_user = os.getenv("SMTP_USERNAME") or os.getenv("SMTP_USER")
        smtp_password = os.getenv("SMTP_PASSWORD")
        sender_email = os.getenv("SENDER_EMAIL") or os.getenv("SMTP_FROM") or smtp_user or "sanjib2119@gmail.com"

        sent_live = False
        if smtp_server and smtp_user and smtp_password:
            try:
                msg = MIMEMultipart("alternative")
                msg["Subject"] = subject
                msg["From"] = f"VPM Platform <{sender_email}>"
                msg["To"] = recipient_email
                msg.attach(MIMEText(html_body, "html"))

                with smtplib.SMTP(smtp_server, smtp_port, timeout=12) as server:
                    server.starttls()
                    server.login(smtp_user, smtp_password)
                    server.sendmail(sender_email, recipient_email, msg.as_string())
                sent_live = True
                logger.info(f"Live SMTP email sent successfully to {recipient_email}")
            except Exception as e:
                logger.warning(f"SMTP send failed ({e}), recording delivery log.")

        # Always record in log for auditable tracing
        logger.info(f"[EMAIL DISPATCH] To: {recipient_email} | Name: {recipient_name} | Role: {role} | Default Password: {default_password} | Live Sent: {sent_live}")
        
        return {
            "email": recipient_email,
            "name": recipient_name,
            "role": role,
            "default_password": default_password,
            "live_smtp_sent": sent_live,
            "status": "Mail Sent"
        }
